import PDFDocument from 'pdfkit';

export default async function handler(req, res) {

  // ── CORS ────────────────────────────────────────────────────
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const debugMode = req.body?.debug === true;
  const log = (...args) => { if (debugMode) console.log('[finalize]', ...args); };

  try {
    const {
      am_id,
      firstName,
      bizName,
      email,
      phone,
      bizDesc,
      challenge,
      stage,
      partnerName,
      roadmap        // { intro, steps: [{title, guidance, whyNow}] }
    } = req.body;

    if (!am_id || !email || !roadmap) {
      return res.status(400).json({ error: 'Missing required fields: am_id, email, roadmap' });
    }

    const supabaseUrl = process.env.SUPABASE_URL;
    const supabaseKey = process.env.SUPABASE_ANON_KEY;

    log('Starting finalize for', { email, bizName });

    // ── 1. Generate PDF buffer ────────────────────────────────
    log('Generating PDF');

    const pdfBuffer = await new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50, size: 'LETTER' });
      const chunks = [];

      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const GREEN  = '#0b8927';
      const NAVY   = '#003366';
      const MUTED  = '#6b7a8d';
      const TEXT   = '#1c2b3a';

      // Header bar
      doc.rect(0, 0, doc.page.width, 70).fill(GREEN);
      doc.fillColor('#ffffff')
         .fontSize(20).font('Helvetica-Bold')
         .text('CoreService Associates', 50, 20);
      doc.fontSize(10).font('Helvetica')
         .text('Your Personal Business Roadmap', 50, 46);

      doc.moveDown(3);

      // Recipient line
      doc.fillColor(NAVY).fontSize(22).font('Helvetica-Bold')
         .text(`${firstName}'s Roadmap`, { align: 'left' });

      if (bizName) {
        doc.fillColor(MUTED).fontSize(12).font('Helvetica')
           .text(bizName, { align: 'left' });
      }

      doc.moveDown(0.5);

      // Intro
      doc.fillColor(TEXT).fontSize(11).font('Helvetica')
         .text(roadmap.intro, { align: 'left', lineGap: 4 });

      doc.moveDown(1.5);

      // Steps
      roadmap.steps.forEach((step, i) => {
        const stepNum = `Step ${i + 1}`;

        // Step number badge (simulate with text)
        doc.fillColor(GREEN).fontSize(10).font('Helvetica-Bold')
           .text(stepNum.toUpperCase(), { continued: false });

        // Step title
        doc.fillColor(NAVY).fontSize(14).font('Helvetica-Bold')
           .text(step.title, { lineGap: 2 });

        doc.moveDown(0.3);

        // Guidance
        doc.fillColor(TEXT).fontSize(11).font('Helvetica')
           .text(step.guidance, { lineGap: 4 });

        doc.moveDown(0.3);

        // Why now
        doc.fillColor(GREEN).fontSize(10).font('Helvetica-Oblique')
           .text(`→ ${step.whyNow}`, { lineGap: 2 });

        doc.moveDown(1.2);

        // Divider between steps (not after last)
        if (i < roadmap.steps.length - 1) {
          const y = doc.y;
          doc.moveTo(50, y).lineTo(doc.page.width - 50, y)
             .strokeColor('#e2e6ea').lineWidth(1).stroke();
          doc.moveDown(1.2);
        }
      });

      // Step 4 — partner CTA box
      doc.moveDown(0.5);
      const boxTop = doc.y;
      const boxWidth = doc.page.width - 100;

      doc.rect(50, boxTop, boxWidth, 90).fill(GREEN);

      doc.fillColor('#ffffff').fontSize(10).font('Helvetica-Bold')
         .text('STEP 4', 66, boxTop + 12);

      doc.fontSize(14).font('Helvetica-Bold')
         .text(`Connect with ${partnerName || 'CoreService Associates'}`, 66, boxTop + 26);

      doc.fontSize(10).font('Helvetica')
         .text(
           `You've got your first three moves — and you don't have to figure out the rest alone. ${partnerName || 'Your CoreService partner'} is a local advisor who already knows your market. A free check-in takes 20 minutes and costs nothing.`,
           66,
           boxTop + 46,
           { width: boxWidth - 32, lineGap: 3 }
         );

      doc.moveDown(5);

      // Footer
      const footerY = doc.page.height - 50;
      doc.moveTo(50, footerY).lineTo(doc.page.width - 50, footerY)
         .strokeColor('#e2e6ea').lineWidth(1).stroke();

      doc.fillColor(MUTED).fontSize(9).font('Helvetica')
         .text(
           `Generated by CoreService Associates · ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
           50,
           footerY + 10,
           { align: 'center', width: doc.page.width - 100 }
         );

      doc.end();
    });

    log('PDF generated, size:', pdfBuffer.length);

    // ── 2. Upload PDF to Supabase Storage ────────────────────
    const safeBizName = (bizName || 'Business')
      .replace(/[^a-zA-Z0-9\s-]/g, '')
      .trim()
      .replace(/\s+/g, '-');
    const fileName = `${safeBizName}-Roadmap-${Date.now()}.pdf`;
    const storagePath = `roadmaps/${fileName}`;

    log('Uploading PDF to Supabase Storage:', storagePath);

    const uploadRes = await fetch(
      `${supabaseUrl}/storage/v1/object/roadmaps/${fileName}`,
      {
        method:  'POST',
        headers: {
          'apikey':        supabaseKey,
          'Authorization': `Bearer ${supabaseKey}`,
          'Content-Type':  'application/pdf',
          'x-upsert':      'true'
        },
        body: pdfBuffer
      }
    );

    if (!uploadRes.ok) {
      const uploadErr = await uploadRes.text();
      console.error('[finalize] Storage upload error:', uploadErr);
      return res.status(500).json({ error: 'PDF upload failed' });
    }

    const pdfUrl = `${supabaseUrl}/storage/v1/object/public/roadmaps/${fileName}`;
    log('PDF uploaded, URL:', pdfUrl);

    // ── 3. Build roadmap plain text for GHL custom field ─────
    const roadmapText = [
      roadmap.intro,
      '',
      ...roadmap.steps.map((step, i) =>
        `Step ${i + 1}: ${step.title}\n${step.guidance}\n→ ${step.whyNow}`
      )
    ].join('\n\n');

    // ── 4. Save submission to Supabase ───────────────────────
    log('Saving submission to Supabase');

    const submissionRecord = {
      am_id,
      first_name:     firstName,
      email,
      phone:          phone || '',
      biz_name:       bizName || '',
      biz_desc:       bizDesc || '',
      challenge:      challenge || '',
      stage:          stage || '',
      roadmap_json:   JSON.stringify(roadmap),
      roadmap_text:   roadmapText,
      pdf_url:        pdfUrl,
      partner_name:   partnerName || '',
      created_at:     new Date().toISOString()
    };

    const saveRes = await fetch(
      `${supabaseUrl}/rest/v1/submissions`,
      {
        method:  'POST',
        headers: {
          'apikey':        supabaseKey,
          'Authorization': `Bearer ${supabaseKey}`,
          'Content-Type':  'application/json',
          'Prefer':        'return=representation'
        },
        body: JSON.stringify(submissionRecord)
      }
    );

    if (!saveRes.ok) {
      const saveErr = await saveRes.text();
      console.error('[finalize] Submission save error:', saveErr);
      // Non-fatal — continue to webhook
    }

    const savedRows = await saveRes.json().catch(() => []);
    const submissionId = savedRows?.[0]?.id || null;
    log('Submission saved, id:', submissionId);

    // ── 5. Fetch affiliate webhook URL ───────────────────────
    const affRes = await fetch(
      `${supabaseUrl}/rest/v1/affiliates?am_id=eq.${encodeURIComponent(am_id)}&active=eq.true&limit=1`,
      {
        headers: {
          'apikey':        supabaseKey,
          'Authorization': `Bearer ${supabaseKey}`,
          'Content-Type':  'application/json'
        }
      }
    );

    const affiliates = await affRes.json();
    if (!affiliates || affiliates.length === 0) {
      return res.status(404).json({ error: `No active affiliate found for am_id: ${am_id}` });
    }

    const affiliate = affiliates[0];
    log('Affiliate found', { name: affiliate.name });

    // ── 6. POST to GHL webhook ───────────────────────────────
    const webhookPayload = {
      firstName:    firstName,
      lastName:     '',
      email:        email,
      phone:        phone || '',
      source:       'CSA Roadmap App',
      tags:         ['CSA-Roadmap-Completed', `affiliate-${am_id}`],
      customFields: {
        am_id,
        bizName:        bizName   || '',
        bizDesc:        bizDesc   || '',
        challenge:      challenge || '',
        stage:          stage     || '',
        roadmapPdfUrl:  pdfUrl,
        roadmapContent: roadmapText
      },
      timestamp: new Date().toISOString()
    };

    log('Firing GHL webhook', { url: affiliate.webhook_url });

    let webhookStatus = 'skipped';
    if (affiliate.webhook_url && !affiliate.webhook_url.includes('PLACEHOLDER')) {
      try {
        const whRes = await fetch(affiliate.webhook_url, {
          method:  'POST',
          headers: { 'Content-Type': 'application/json' },
          body:    JSON.stringify(webhookPayload)
        });
        webhookStatus = whRes.ok ? 'success' : `failed (${whRes.status})`;
        log('Webhook response:', webhookStatus);
      } catch (whErr) {
        webhookStatus = `error: ${whErr.message}`;
        console.error('[finalize] Webhook error:', whErr.message);
      }
    } else {
      log('Webhook skipped — placeholder or missing URL');
    }

    // ── 7. Return success ────────────────────────────────────
    return res.status(200).json({
      success: true,
      pdfUrl,
      submissionId,
      webhookStatus,
      ...(debugMode && {
        _debug: { roadmapText, webhookPayload, webhookStatus }
      })
    });

  } catch (err) {
    console.error('[finalize] Unhandled error:', err);
    return res.status(500).json({
      error: 'Internal server error',
      ...(req.body?.debug && {
        _debug: { message: err.message, stack: err.stack }
      })
    });
  }
}
